import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SALU",
  description: "Generated by create next app",
  openGraph: {
    title: "SALU",
    description: "una plataforma que ofrece microcréditos y opciones de ahorro digital para que las consultas médicas y odontológicas",
    type: "website",
    images: {
      url: "/previewSalu.png",
      width: "1200",
      height: "630",
    },
    siteName: "Unidotaciones del Caribe",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className} antialiased bg-white text-black`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
