import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "sonner";
import { CreditApplicationProvider } from "@/contexts/CreditApplicationContext";

const manrope = Manrope({ subsets: ["latin"] });

const noken = localFont({
  src: [
    {
      path: './fonts/Noken.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Nokenbold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/Nokensemibold.ttf',
      weight: '600',
      style: 'normal',
    },
  ],
  variable: '--font-noken',
});

export const metadata: Metadata = {
  title: "SALU",
  description: "Generated by create next app",
  openGraph: {
    title: "SALU",
    description: "una plataforma que ofrece microcréditos y opciones de ahorro digital para que las consultas médicas y odontológicas",
    type: "website",
    images: {
      url: "/previewSalu.png",
      width: "1200",
      height: "630",
    },
    siteName: "Unidotaciones del Caribe",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <CreditApplicationProvider>
          {children}
        </CreditApplicationProvider>
        <Toaster />
      </body>
    </html>
  );
}
