import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { Navbar } from "@/components/layout/Nav";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SALU",
  description: "Generated by create next app",
  openGraph: {
    title: "SALU",
    description: "una plataforma que ofrece microcréditos y opciones de ahorro digital para que las consultas médicas y odontológicas",
    type: "website",
    images: {
      url: "https://firebasestorage.googleapis.com/v0/b/unidotaciones-f49fc.appspot.com/o/SaluPrevie.png?alt=media&token=4e25c1f5-a3da-4598-9126-caef75d7f50c",
      width: "1200",
      height: "630",
    },
    siteName: "Unidotaciones del Caribe",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className} antialiased bg-white text-black`}
      >
        <Navbar />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
